using System.Globalization;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;
using OFS.Sdk;

return ApiSurfaceProgram.Run(args);

internal static class ApiSurfaceProgram
{
    internal const int FormatVersion = 1;

    internal static int Run(string[] args)
    {
        if (args.Length != 2 || args[0] is not ("verify" or "accept"))
        {
            Console.Error.WriteLine(
                "Usage: OFS.Sdk.ApiSurface <verify|accept> <PublicAPI.Shipped.txt>");
            return 2;
        }

        var baselinePath = Path.GetFullPath(args[1]);
        var current = PublicApiSurface.Generate(typeof(IOFSMod).Assembly);
        if (args[0] == "accept")
        {
            Directory.CreateDirectory(Path.GetDirectoryName(baselinePath)!);
            File.WriteAllText(baselinePath, current, new UTF8Encoding(false));
            Console.WriteLine($"Accepted OFS.Sdk public API baseline: {baselinePath}");
            return 0;
        }

        if (!File.Exists(baselinePath))
        {
            Console.Error.WriteLine(
                $"Public API baseline is missing: {baselinePath}{Environment.NewLine}" +
                "Run the accept command after reviewing the current surface.");
            return 1;
        }

        var baseline = Normalize(File.ReadAllText(baselinePath));
        if (string.Equals(baseline, current, StringComparison.Ordinal))
        {
            Console.WriteLine(
                $"OFS.Sdk public API matches baseline " +
                $"({PublicApiSurface.CountSignatures(current)} signatures).");
            return 0;
        }

        Console.Error.WriteLine("OFS.Sdk public API differs from its shipped baseline.");
        PrintDifference(baseline, current);
        Console.Error.WriteLine(
            "Review the change, apply semantic versioning, then run the accept command intentionally.");
        return 1;
    }

    private static string Normalize(string value) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal).TrimEnd() + "\n";

    private static void PrintDifference(string baseline, string current)
    {
        var expected = baseline.Split('\n');
        var actual = current.Split('\n');
        var prefix = 0;
        while (prefix < expected.Length && prefix < actual.Length &&
               expected[prefix] == actual[prefix]) ++prefix;
        var expectedSuffix = expected.Length - 1;
        var actualSuffix = actual.Length - 1;
        while (expectedSuffix >= prefix && actualSuffix >= prefix &&
               expected[expectedSuffix] == actual[actualSuffix])
        {
            --expectedSuffix;
            --actualSuffix;
        }

        Console.Error.WriteLine($"First changed line: {prefix + 1}");
        foreach (var line in expected.Skip(prefix).Take(Math.Min(40, expectedSuffix - prefix + 1)))
            Console.Error.WriteLine($"- {line}");
        foreach (var line in actual.Skip(prefix).Take(Math.Min(40, actualSuffix - prefix + 1)))
            Console.Error.WriteLine($"+ {line}");
        if (expectedSuffix - prefix + 1 > 40 || actualSuffix - prefix + 1 > 40)
            Console.Error.WriteLine("... difference truncated ...");
    }
}

internal static class PublicApiSurface
{
    private static readonly NullabilityInfoContext Nullability = new();
    private static readonly BindingFlags DeclaredApi =
        BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance |
        BindingFlags.Static | BindingFlags.DeclaredOnly;

    internal static string Generate(Assembly assembly)
    {
        var version = assembly.GetName().Version
            ?? throw new InvalidOperationException("OFS.Sdk assembly has no version.");
        var sdkVersion = new Version(version.Major, version.Minor, version.Build);
        if (ModManifestValidator.CurrentSdkVersion != sdkVersion)
            throw new InvalidOperationException(
                $"SDK assembly version {sdkVersion} differs from " +
                $"ModManifestValidator.CurrentSdkVersion {ModManifestValidator.CurrentSdkVersion}.");

        var lines = new List<string>
        {
            "# OFS.Sdk public API baseline",
            "# Generated by tests/OFS.Sdk.ApiSurface; do not edit manually.",
            $"# FormatVersion: {ApiSurfaceProgram.FormatVersion}",
            $"# SdkVersion: {sdkVersion}",
            string.Empty,
        };
        foreach (var type in assembly.GetTypes()
                     .Where(IsVisible)
                     .OrderBy(TypeIdentity, StringComparer.Ordinal))
        {
            lines.Add(FormatTypeDeclaration(type));
            lines.AddRange(GetMemberDeclarations(type)
                .OrderBy(value => value, StringComparer.Ordinal));
            lines.Add(string.Empty);
        }
        return string.Join('\n', lines).TrimEnd() + "\n";
    }

    internal static int CountSignatures(string surface) => surface.Split('\n').Count(
        line => line.Length > 0 && !line.StartsWith('#'));

    private static bool IsVisible(Type type) => type.IsPublic || type.IsNestedPublic ||
        type.IsNestedFamily || type.IsNestedFamORAssem;

    private static string TypeIdentity(Type type) =>
        type.FullName ?? type.Name;

    private static string FormatTypeDeclaration(Type type)
    {
        var builder = new StringBuilder("type ");
        AppendVisibility(builder, type);
        if (type.IsAbstract && type.IsSealed) builder.Append("static ");
        else
        {
            if (type.IsAbstract && !type.IsInterface) builder.Append("abstract ");
            if (type.IsSealed && !type.IsValueType && !type.IsEnum) builder.Append("sealed ");
        }
        if (type.IsDefined(typeof(IsReadOnlyAttribute), false)) builder.Append("readonly ");
        builder.Append(type.IsInterface ? "interface " :
            type.IsEnum ? "enum " :
            IsDelegate(type) ? "delegate " :
            type.IsValueType ? "struct " : "class ");
        builder.Append(FormatTypeName(type));
        if (type.IsEnum)
            builder.Append(" : ").Append(FormatTypeName(Enum.GetUnderlyingType(type)));
        else if (!IsDelegate(type))
        {
            var bases = new List<Type>();
            if (type.BaseType is { } baseType &&
                baseType != typeof(object) && baseType != typeof(ValueType))
                bases.Add(baseType);
            bases.AddRange(type.GetInterfaces().OrderBy(TypeIdentity, StringComparer.Ordinal));
            if (bases.Count > 0)
                builder.Append(" : ").Append(string.Join(", ", bases.Select(value => FormatTypeName(value))));
        }
        AppendGenericConstraints(builder, type.GetGenericArguments());
        return builder.ToString();
    }

    private static IEnumerable<string> GetMemberDeclarations(Type type)
    {
        var owner = FormatTypeName(type);
        if (type.IsEnum)
        {
            foreach (var field in type.GetFields(BindingFlags.Public | BindingFlags.Static))
                yield return $"field {owner} :: {field.Name} = {FormatConstant(field.GetRawConstantValue(), field.FieldType)}";
            yield break;
        }

        foreach (var constructor in type.GetConstructors(DeclaredApi).Where(IsApiVisible))
            yield return $"ctor {owner} :: {FormatVisibility(constructor)}({FormatParameters(constructor.GetParameters())})";

        foreach (var field in type.GetFields(DeclaredApi).Where(IsApiVisible))
        {
            var modifiers = new StringBuilder(FormatVisibility(field));
            if (field.IsStatic) modifiers.Append(" static");
            if (field.IsLiteral) modifiers.Append(" const");
            else if (field.IsInitOnly) modifiers.Append(" readonly");
            if (field.IsDefined(typeof(RequiredMemberAttribute), false)) modifiers.Append(" required");
            var value = field.IsLiteral
                ? $" = {FormatConstant(field.GetRawConstantValue(), field.FieldType)}"
                : string.Empty;
            yield return $"field {owner} :: {modifiers} {FormatTypeName(field.FieldType)} {field.Name}{value}";
        }

        foreach (var property in type.GetProperties(DeclaredApi).Where(IsApiVisible))
        {
            var accessor = property.GetMethod ?? property.SetMethod!;
            var modifiers = new StringBuilder(FormatVisibility(accessor));
            if (accessor.IsStatic) modifiers.Append(" static");
            if (accessor.IsAbstract) modifiers.Append(" abstract");
            else if (accessor.IsVirtual && !accessor.IsFinal) modifiers.Append(" virtual");
            if (property.IsDefined(typeof(RequiredMemberAttribute), false)) modifiers.Append(" required");
            var index = property.GetIndexParameters();
            var name = index.Length == 0
                ? property.Name
                : $"this[{FormatParameters(index)}]";
            var accessors = new List<string>();
            if (property.GetMethod is { } getter && IsApiVisible(getter))
                accessors.Add($"{AccessorPrefix(accessor, getter)}get;");
            if (property.SetMethod is { } setter && IsApiVisible(setter))
            {
                var init = setter.ReturnParameter.GetRequiredCustomModifiers()
                    .Contains(typeof(IsExternalInit));
                accessors.Add($"{AccessorPrefix(accessor, setter)}{(init ? "init" : "set")};");
            }
            yield return $"property {owner} :: {modifiers} " +
                $"{FormatTypeName(property.PropertyType, Nullability.Create(property))} {name} " +
                $"{{ {string.Join(' ', accessors)} }}";
        }

        foreach (var eventInfo in type.GetEvents(DeclaredApi).Where(IsApiVisible))
        {
            var accessor = eventInfo.AddMethod ?? eventInfo.RemoveMethod!;
            var modifiers = new StringBuilder(FormatVisibility(accessor));
            if (accessor.IsStatic) modifiers.Append(" static");
            yield return $"event {owner} :: {modifiers} " +
                $"{FormatTypeName(eventInfo.EventHandlerType!)} {eventInfo.Name}";
        }

        foreach (var method in type.GetMethods(DeclaredApi)
                     .Where(method => IsApiVisible(method) && !method.IsSpecialName))
        {
            var modifiers = new StringBuilder(FormatVisibility(method));
            if (method.IsStatic) modifiers.Append(" static");
            if (method.IsAbstract) modifiers.Append(" abstract");
            else if (method.IsVirtual && !method.IsFinal) modifiers.Append(" virtual");
            var generic = method.IsGenericMethodDefinition
                ? $"<{string.Join(", ", method.GetGenericArguments().Select(value => value.Name))}>"
                : string.Empty;
            var builder = new StringBuilder()
                .Append("method ").Append(owner).Append(" :: ")
                .Append(modifiers).Append(' ')
                .Append(FormatTypeName(method.ReturnType, Nullability.Create(method.ReturnParameter)))
                .Append(' ').Append(method.Name).Append(generic)
                .Append('(').Append(FormatParameters(method.GetParameters())).Append(')');
            AppendGenericConstraints(builder, method.GetGenericArguments());
            yield return builder.ToString();
        }
    }

    private static string AccessorPrefix(MethodInfo primary, MethodInfo accessor) =>
        FormatVisibility(primary) == FormatVisibility(accessor)
            ? string.Empty
            : FormatVisibility(accessor) + " ";

    private static bool IsApiVisible(MethodBase method) => method.IsPublic || method.IsFamily || method.IsFamilyOrAssembly;
    private static bool IsApiVisible(FieldInfo field) => field.IsPublic || field.IsFamily || field.IsFamilyOrAssembly;
    private static bool IsApiVisible(PropertyInfo property) =>
        (property.GetMethod is { } get && IsApiVisible(get)) ||
        (property.SetMethod is { } set && IsApiVisible(set));
    private static bool IsApiVisible(EventInfo eventInfo) =>
        (eventInfo.AddMethod is { } add && IsApiVisible(add)) ||
        (eventInfo.RemoveMethod is { } remove && IsApiVisible(remove));

    private static void AppendVisibility(StringBuilder builder, Type type)
    {
        builder.Append(type.IsPublic || type.IsNestedPublic ? "public " :
            type.IsNestedFamily ? "protected " : "protected internal ");
    }

    private static string FormatVisibility(MethodBase method) => method.IsPublic
        ? "public"
        : method.IsFamily ? "protected" : "protected internal";
    private static string FormatVisibility(FieldInfo field) => field.IsPublic
        ? "public"
        : field.IsFamily ? "protected" : "protected internal";

    private static string FormatParameters(ParameterInfo[] parameters) =>
        string.Join(", ", parameters.Select(FormatParameter));

    private static string FormatParameter(ParameterInfo parameter)
    {
        var type = parameter.ParameterType;
        var modifier = string.Empty;
        if (type.IsByRef)
        {
            modifier = parameter.IsOut ? "out " : parameter.IsIn ? "in " : "ref ";
            type = type.GetElementType()!;
        }
        else if (parameter.GetCustomAttribute<ParamArrayAttribute>() is not null)
            modifier = "params ";
        var nullable = Nullability.Create(parameter);
        var result = $"{modifier}{FormatTypeName(type, nullable)} {parameter.Name}";
        if (parameter.HasDefaultValue)
            result += $" = {FormatConstant(parameter.DefaultValue, type)}";
        return result;
    }

    private static string FormatTypeName(Type type, NullabilityInfo? nullable = null)
    {
        if (type.IsByRef || type.IsPointer)
            return FormatTypeName(type.GetElementType()!, nullable?.ElementType) + (type.IsPointer ? "*" : string.Empty);
        if (type.IsArray)
            return FormatTypeName(type.GetElementType()!, nullable?.ElementType) +
                $"[{new string(',', type.GetArrayRank() - 1)}]" + NullableSuffix(type, nullable);
        if (Nullable.GetUnderlyingType(type) is { } underlying)
            return FormatTypeName(underlying, nullable?.GenericTypeArguments.FirstOrDefault()) + "?";
        if (Aliases.TryGetValue(type, out var alias)) return alias + NullableSuffix(type, nullable);
        if (type.IsGenericParameter) return type.Name + NullableSuffix(type, nullable);

        var name = type.IsNested
            ? FormatTypeName(type.DeclaringType!) + "." + StripArity(type.Name)
            : (string.IsNullOrEmpty(type.Namespace) ? string.Empty : type.Namespace + ".") + StripArity(type.Name);
        if (type.IsGenericType)
        {
            var declaringCount = type.IsNested && type.DeclaringType!.IsGenericType
                ? type.DeclaringType.GetGenericArguments().Length
                : 0;
            var arguments = type.GetGenericArguments().Skip(declaringCount).ToArray();
            var nullableArguments = nullable?.GenericTypeArguments.Skip(declaringCount).ToArray();
            if (arguments.Length > 0)
                name += $"<{string.Join(", ", arguments.Select((value, index) =>
                    FormatTypeName(value, nullableArguments?.ElementAtOrDefault(index))))}>";
        }
        return name + NullableSuffix(type, nullable);
    }

    private static string NullableSuffix(Type type, NullabilityInfo? nullable) =>
        !type.IsValueType && nullable?.ReadState == NullabilityState.Nullable ? "?" : string.Empty;

    private static string StripArity(string name)
    {
        var tick = name.IndexOf('`');
        return tick < 0 ? name : name[..tick];
    }

    private static void AppendGenericConstraints(StringBuilder builder, Type[] arguments)
    {
        foreach (var argument in arguments.Where(value => value.IsGenericParameter))
        {
            var constraints = new List<string>();
            var attributes = argument.GenericParameterAttributes;
            if (attributes.HasFlag(GenericParameterAttributes.ReferenceTypeConstraint)) constraints.Add("class");
            if (attributes.HasFlag(GenericParameterAttributes.NotNullableValueTypeConstraint)) constraints.Add("struct");
            constraints.AddRange(argument.GetGenericParameterConstraints().Select(value => FormatTypeName(value)));
            if (attributes.HasFlag(GenericParameterAttributes.DefaultConstructorConstraint) &&
                !attributes.HasFlag(GenericParameterAttributes.NotNullableValueTypeConstraint))
                constraints.Add("new()");
            if (constraints.Count > 0)
                builder.Append(" where ").Append(argument.Name).Append(" : ")
                    .Append(string.Join(", ", constraints));
        }
    }

    private static string FormatConstant(object? value, Type declaredType)
    {
        if (value is null || value == DBNull.Value || value == Missing.Value) return "null";
        if (declaredType.IsEnum)
        {
            var name = Enum.GetName(declaredType, value);
            var underlying = Enum.GetUnderlyingType(declaredType);
            var number = underlying == typeof(byte) || underlying == typeof(ushort) ||
                         underlying == typeof(uint) || underlying == typeof(ulong)
                ? Convert.ToUInt64(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture)
                : Convert.ToInt64(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture);
            return name is null
                ? $"({FormatTypeName(declaredType)}){number}"
                : $"{FormatTypeName(declaredType)}.{name} ({number})";
        }
        return value switch
        {
            string text => JsonSerializer.Serialize(text),
            char character => $"'{character}'",
            bool boolean => boolean ? "true" : "false",
            float number => number.ToString("R", CultureInfo.InvariantCulture) + "f",
            double number => number.ToString("R", CultureInfo.InvariantCulture),
            decimal number => number.ToString(CultureInfo.InvariantCulture) + "m",
            _ => Convert.ToString(value, CultureInfo.InvariantCulture) ?? "null",
        };
    }

    private static bool IsDelegate(Type type) =>
        type.BaseType is { } baseType && typeof(MulticastDelegate).IsAssignableFrom(baseType);

    private static readonly IReadOnlyDictionary<Type, string> Aliases = new Dictionary<Type, string>
    {
        [typeof(void)] = "void",
        [typeof(bool)] = "bool",
        [typeof(byte)] = "byte",
        [typeof(sbyte)] = "sbyte",
        [typeof(short)] = "short",
        [typeof(ushort)] = "ushort",
        [typeof(int)] = "int",
        [typeof(uint)] = "uint",
        [typeof(long)] = "long",
        [typeof(ulong)] = "ulong",
        [typeof(float)] = "float",
        [typeof(double)] = "double",
        [typeof(decimal)] = "decimal",
        [typeof(char)] = "char",
        [typeof(string)] = "string",
        [typeof(object)] = "object",
        [typeof(nint)] = "nint",
        [typeof(nuint)] = "nuint",
    };
}
